version = 0.1
[default.deploy.parameters]
stack_name = "ConfirmLambda"
resolve_s3 = true
s3_prefix = "ConfirmLambda"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SenderEmail=\"licinio@gmail.com\""
